### ISSUE TITLE
Option to remap copy

### ISSUE THREAD

**Issue by adrianbill** [SUPERCILEX/gnome-clipboard-history#117]
Include option to remap the copy command to the same as the paste.
Within the extension I have "toggle menu" mapped to "Super+v"
I would love to be able to use "Super+C" to copy text instead of switching to "Ctrl+C" for this.

**Comment by SUPERCILEX** [comment]
This isn't possible unfortunately: each application defines its own copy/paste shortcuts and uses them to send/receive clipboard events. This extension just receives clipboard events (where the paste-on-click implementation is a total hack since we hope the application will understand the key events we send it which it sometimes doesn't), so I don't think the extension can request a copy from an application. You could try changing the shortcuts for each application: https://askubuntu.com/questions/39462/how-do-i-reconfigure-keyboard-shortcuts-for-copy-and-paste?rq=1
