### ISSUE TITLE
Focus the 2nd last when using the menu shortcut

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [SUPERCILEX/gnome-clipboard-history#142]
### Problem description
I set the shortcut to open the clipboard to `Super` + `V`. I use it to paste the 2nd or earlier item (since for the first item I can just to Ctrl + V). Instead of focusing on the search box, I want it to focus on the 2nd last item.

Instead of this:
![image](https://github.com/SUPERCILEX/gnome-clipboard-history/assets/52586855/2739af84-b386-44c3-bc60-23bf5033d540)

I want this:
![image](https://github.com/SUPERCILEX/gnome-clipboard-history/assets/52586855/80a84d59-1921-4be5-a910-d03736bc5613)

### Potential solutions/workarounds
- Add a dropdown option that says: "Focus when opening menu"
  - "Search Input"
  - "2nd last item"
- Add a number input which let's you focus on the n-th last item

**Comment by SUPERCILEX** [comment]
Yup, that's what the Ctrl+N keys are for. To paste "a", you would just use Ctrl+2. Doesn't actually work in chrome because gnome sucks, but it will at least be copied to your clipboard so you can then paste it (and it does work in the terminal for example).

I gave skipping the first item some thought and decided against it because that behavior would be weird if you have favorites and it's possible you want to delete the first item so skipping it would be annoying in that case.
