### ISSUE TITLE
Doesn't save entries

### ISSUE THREAD

**Issue by gjm** [SUPERCILEX/gnome-clipboard-history#67]
### Describe the bug

When I copy text it isn't saved into the clipboard history.

#### Versions

GNOME Shell 40.5
GCH   Version: 15
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history history-size 50
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history strip-text true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history paste-on-selection false
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super><Shift>V']
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history window-width-percentage 33
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history prev-entry @as []

#### Steps to repro

Select and copy text. Open the extension menu and verify the copied text is missing.

**Comment by SUPERCILEX** [comment]
It's probably a crash, so can you run this: ```sh
journalctl -n 1000000 | grep -B 10 -A 10 'clipboard-history'
```

**Comment by gjm** [comment]
I think this the relevant part:

```
JS ERROR: TypeError: undefined has no properties
loop/<@/home/gjm/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:144:56
parseAvailableAware@/home/gjm/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:189:7
loop@/home/gjm/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:142:26
loop/<@/home/gjm/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:137:11
```

**Comment by SUPERCILEX** [comment]
Ah, that means the database is corrupted. If you're comfortable sending me your clipboard history, you can email or upload an encrypted version of the database:

```sh
curl -L alexsaveau.dev/gpg -o supercilex.key && gpg --output database.enc --encrypt --recipient-file supercilex.key ~/.cache/clipboard-history@alexsaveau.dev/database.log && rm supercilex.key
```

If you just want to get things working again, you can `rm ~/.cache/clipboard-history@alexsaveau.dev/database.log` but you'll lose all your data and I won't be able to look into what went wrong.

**Comment by SUPERCILEX** [comment]
Closing since there's nothing I can do.

**Comment by mlncn** [comment]
Same thing happened to me.  I also shouldn't be sending my `~/.cache/clipboard-history@alexsaveau.dev/database.log` but taking a peek in myself.

Looks like the separator changed from:

`^@^A`

To:

`^@^B^A^@^@^@^A` and `^@^B^B^@^@^@^A` and `^@^B^C^@^@^@^A` going through the alphabet like that, getting up to `G` for the third character before we get a really weird one:

`^@^B^G^@^@^@^E<D0>^C^@^@^E<D0>^C^@^@^A`

(And that is definitely a separator, and came *after* `^@^B^G^@^@^@^A` used as a separator.)

Then it was back to the alphabetical pattern with `^@^B^H^@^@^@^A` and — well this part starting with the `H` separator there i can quote in full:

```
^@^B^H^@^@^@^Ahttps://servers.coop/^@^B   ^@^@^@^Ahttps://drutopia.org^@^B
^@^@^@^AAgaric seriously interested in stepping up in managed hosting— we've been doing it for all clients since 2^@^B^K^@^@^@^AWhose the dr^@^B^L^@^@^@^A
```

And after the `L` separator, `M`, `N`, `O` and the file ends with an ordinary-for-the-pattern looking:

```
state-homeless-commission-meeting.md^@^B^P^@^@^@
```

No new entries are being added to this file, and the clipboard interface does not show any entries at all.

A dozen or so entries before the `^@^A` separator stopped, there was a very long copy, and another entry with an emoji, but otherwise nothing of note scrolling back a ways.

**Comment by SUPERCILEX** [comment]
Hey, thanks for investigating! Presumably you're looking at stuff through a text editor which isn't going to be useful since the database is a binary format. I just added a tool to dump the db metadata. Can you run it and share the output? It should pinpoint where things went wrong:

```shell
$ git clone git@github.com:SUPERCILEX/gnome-clipboard-history.git
$ cd gnome-clipboard-history/tools
# If you don't have rust installed:
$ curl https://sh.rustup.rs -sSf | sh
$ cargo r -- dump > dump.txt
# Run this instead if you moved the database somewhere else:
$ cargo r -- dump path/to/db > dump.txt
```

Upload dump.txt. Also, it will probably fail since the db is corrupted so sharing the dump crash would also be helpful.
